//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcGooglemapDb1.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Employee
    {
        public int ID { get; set; }

        [Required(ErrorMessage ="*First Name and Last Name Required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "*City is Required")]
        public string City { get; set; }

        [Required(ErrorMessage = "*State is Required")]
        public string State { get; set; }

        [Required(ErrorMessage = "*Enter Valid PinCode Required")]
        [MinLength(6,ErrorMessage ="*PinCode must be of 6 digit")]
        [MaxLength(6, ErrorMessage = "*PinCode must not exceed 6 digit")]
        public string Pincode { get; set; }

        [Required(ErrorMessage = "*Latitude Required")]
        public Nullable<decimal> Latitude { get; set; }
        [Required(ErrorMessage = "*Longitude Required")]
        public Nullable<decimal> Longitude { get; set; }

        public string Description { get; set; }
    }
}
